### PR TITLE
add linkedin example and allow token_type to be empty

### PR DESCRIPTION
**Pull request by extrawurst**
empty or no token_type is interpreted as 'bearer' (linked.in api does not return a token_type but uses bearer)

### CODE REVIEW

**Comment by extrawurst** [comment]
```
source/oauth/exception.d(53,5): Warning: Ddoc: parameter count mismatch
source/oauth/exception.d(71,5): Warning: Ddoc: parameter count mismatch
```
I did not touch those. but adding them does not fix the issue since it is based on scod or whatever that is not compatible with current dmd. so i will leave this as is.

**Comment by extrawurst** [comment]
The actual unittest and build is fine. its just the ddox that is broken, but it is broken in master already

**Comment by thaven** [comment]
Thanks for your PR. Looks good at first sight, I'll have a look at it in more detail at a later moment.

**Comment by thaven** [comment]
Build failure seems related to https://github.com/MartinNowak/scod/issues/13

**Comment by extrawurst** [comment]
@thaven yup it must be the same in master. let me know if u find any issues that keeps this from being merged please

**Review by thaven — APPROVED** [review]

**Pull request merged**
